
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://sllmwfflpxzicrrrekhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbG13ZmZscHh6aWNycnJla2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODIxNDIsImV4cCI6MjA1OTU1ODE0Mn0.L3QVXjAfPfD0pxeDpnaZuV1k8e3RbU-J0WM39Fq0yts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'nuvos-auth-token'
  }
});
